#pragma once
#define ANIMATION_SET_SIMON	1
#define ANIMATION_SET_BRICK	2
#define	ANIMATION_SET_WHIP	3
#define ANIMATION_SET_DAGGER	4
#define	ANIMATION_SET_CROSS	5
#define ANIMATION_SET_AXE	6
#define ANIMATION_SET_HOLYWATER	7
#define ANIMATION_SET_CANDLE	8
#define ANIMATION_SET_FIREPILLAR	9
#define ANIMATION_SET_SMALLHEART	11
#define ANIMATION_SET_BIGHEART	12
#define ANIMATION_SET_MONEYBAG	13
#define ANIMATION_SET_ORB	14
#define ANIMATION_SET_WHIPUPGRD	15
#define ANIMATION_SET_IDAGGER	16
#define ANIMATION_SET_IAXE	17
#define ANIMATION_SET_IHOLYWATER	18
#define ANIMATION_SET_ICROSS	19
#define ANIMATION_SET_STOPWATCH	20
#define ANIMATION_SET_WEAPONUPGRD	21
#define ANIMATION_SET_CHICKEN	22
#define ANIMATION_SET_BOTTLE	23
#define ANIMATION_SET_ROSARY	24

#define STAGE_1_X 50
#define STAGE_1_Y 128

#define STAGE_2_X 30
#define STAGE_2_Y 144

#define STAGE_3_X 450
#define STAGE_3_Y 79

#define STAGE_4_X 704
#define STAGE_4_Y 128

#define STAGE_5_X 32
#define STAGE_5_Y 128

#define STAGE_6_X 40
#define STAGE_6_Y 48